config/routes.rb
Rails.application.routes.draw do
  get 'baskets/show'

  mount Attachinary::Engine => "/attachinary"

  devise_for :buyers, controllers: { registrations: "registrations", omniauth_callbacks: 'buyers/omniauth_callbacks' }
  devise_for :sellers, controllers: { registrations: "registrations" }

  resources :buyers do
    resources :orders, only: [:new, :update]
  end

  resources :sellers do
    resources :products, only: [:index, :new, :create, :edit, :update]
    resources :orders, only: [:index, :show, :edit, :update]
  end
  resources :products, only: [:index, :show, :edit, :update, :destroy]
  resources :categories
  resources :orders, only: [:index, :show, :edit, :update]
  resources :baskets


  post "add_item/", to: "baskets#add_item"
  post "destroy_cookies_item/:product_id", to: "baskets#destroy_cookies_item", as: 'cookies'

  get "search", to: "products#search"

  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/seller.rb
class Seller < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :company_logo, PhotoUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :products
  has_many :baskets, through: :products
  has_many :orders, through: :baskets
  validates :email, uniqueness: true, presence: true
  validates :company_name, uniqueness: true, allow_nil: true
  # validates :first_name, presence: true
  # validates :last_name, presence: true
  # validates :address, presence: true
  # validates :description, presence: true
  # validates :delivery_time, presence: true
  # validates :delivery_fee, presence: true




end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController

  before_action :set_seller, only:[:edit, :update, :show]

  def index
    # si la company_name commence par la lettre cliquée elle nous renvoie la liste de ces companys
    # sinon elle nous montre toute la liste des companys par ordre alphabetique
    if params[:company_name]
      @sellers = Seller.where "company_name ILIKE ?", "#{params[:company_name]}%"
    else
      @sellers = Seller.all.order('company_name')
    end
  end

  def edit
  end

  def update
    @seller = @seller.update(seller_params)
    redirect_to products_path
  end

  def show
  end

   private

  def seller_params
    params.require(:seller).permit(:first_name, :last_name, :email, :address, :password, :description, :website, :company_name, :company_logo, :company_logo_cache)
  end

  def set_seller
    @seller = Seller.find(params[:id])
  end
end

app/views/sellers/_form.erb
<div id="container-form">
    <%= simple_form_for (@seller) do |f| %>
        <div class="form-group">
          <%= f.input :company_logo, label: "Logo de Société" %>
          <%= f.input :company_logo_cache, as: :hidden %>
          <% if !current_page?(new_seller_path) %>
            <% if !@seller.company_logo.nil?%>
              <%= cl_image_tag @seller.company_logo.url(:thumbnail) %>
            <% end %>
          <% end %>

        </div>
        <div class="form-group">
          <%= f.input :company_name, label: "Nom de Société" %>
        </div>
        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description %>
        </div>
        <div class="form-group">
          <%= f.input :website, label: "Site Web"  %>
        </div>
        <div class="form-group">
          <%= f.input :last_name, label: "Nom de famille" %>
        </div>
        <div class="form-group">
          <%= f.input :first_name, label: "Prénom" %>
        </div>
        <div class="form-group">
          <%= f.input :email %>
        </div>
        <div class="form-group">
          <%= f.input :address, label: "Adresse" %>
        </div>
        <div class="form-group">
          <%= f.input :delivery_time, label: "Délai de livraison" %>
        </div>
        <div class="form-group">
          <%= f.input :delivery_fee, label: "Frais de livraison" %>
        </div>
        <div class="form-group">
          <%= f.input :delivery_free_from, label: "Livraison gratuite à partir de :" %>

        </div>
        <div class="form-group">
        <%= f.submit "Confirmer", class: "btn btn-primary" %>
        </div>
        <% end %>
</div>

app/views/sellers/_private_profile.erb
    <h3>Mes Infos</h3>
    <div class="container">
      <%= render "form" %>
    </div>

app/views/sellers/_public_profile.erb
PRODUCT GRID LAYOUT
<div class="container">
  <div class="picture"></div>
  <div class="info">
    <div class="name"> </div>
    <div class="rating"></div>
    <div class="links"></div>
  </div>
</div>

<div class="container">
  <div class="row">
    <% @seller.products.each do |product| %>
        <div class="col-xs-12 col-sm-4">
          <div class="card">
            <%= link_to product_path(product) do %>
              <div class="card-body">

               </div>
              <div class="card-name">
                <%= product.name %>
              </div>
            <% end %>
          </div>
        </div>
        <% end %>
  </div>
</div>

app/views/sellers/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1>Modifier mon profile Marchand</h1>
</div>


<div class="row">
  <div class="col-md-6 col-md-offset-3">
        <%= render "form" %>
  </div>
</div>

app/views/sellers/index.html.erb
<div class="col-md-6 col-md-offset-3">
<h1>Nos Marchands</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3" >
<!-- Un lien a été fait via chaque lettre au companys commençant par cette même lettre  -->
     <h6>
      <%=link_to 'A', sellers_path(company_name: 'A') %> |
      <%=link_to 'B', sellers_path(company_name: 'B') %> |
      <%=link_to 'C', sellers_path(company_name: 'C') %> |
      <%=link_to 'D', sellers_path(company_name: 'D') %> |
      <%=link_to 'E', sellers_path(company_name: 'E') %> |
      <%=link_to 'F', sellers_path(company_name: 'F') %> |
      <%=link_to 'G', sellers_path(company_name: 'G') %> |
      <%=link_to 'H', sellers_path(company_name: 'H') %> |
      <%=link_to 'I', sellers_path(company_name: 'I') %> |
      <%=link_to 'J', sellers_path(company_name: 'J') %> |
      <%=link_to 'K', sellers_path(company_name: 'K') %> |
      <%=link_to 'L', sellers_path(company_name: 'L') %> |
      <%=link_to 'M', sellers_path(company_name: 'M') %> |
      <%=link_to 'N', sellers_path(company_name: 'N') %> |
      <%=link_to 'O', sellers_path(company_name: 'O') %> |
      <%=link_to 'P', sellers_path(company_name: 'P') %> |
      <%=link_to 'Q', sellers_path(company_name: 'Q') %> |
      <%=link_to 'R', sellers_path(company_name: 'R') %> |
      <%=link_to 'S', sellers_path(company_name: 'S') %> |
      <%=link_to 'T', sellers_path(company_name: 'T') %> |
      <%=link_to 'U', sellers_path(company_name: 'U') %> |
      <%=link_to 'V', sellers_path(company_name: 'V') %> |
      <%=link_to 'W', sellers_path(company_name: 'W') %> |
      <%=link_to 'X', sellers_path(company_name: 'X') %> |
      <%=link_to 'Y', sellers_path(company_name: 'Y') %> |
      <%=link_to 'Z', sellers_path(company_name: 'Z') %> |
    </h6>

  <ul>
    <% @sellers.each do |c| %>
    <!-- je veux afficher que les sellers qui ont au moins 1 produits + un nom de société-->
      <% if c.products.count > 0 && c.company_name != nil %>
        <li> <%= link_to seller_path(c) do %>
          <%= "#{c.company_name} (#{c.products.count} Products)"%> </li>
        <% end %>
      <% end %>
    <% end %>

  </ul>
  </div>
</div>

app/views/sellers/show.html.erb
<!-- For seller to have personal page to update profile etc... -->
<% if @seller == current_seller %>

  <%= render "private_profile" %>

<!-- for PUBLIC seller profile -->
<% else  %>

  <%= render "public_profile" %>

<% end  %>