config/routes.rb
Rails.application.routes.draw do
  get 'baskets/show'

  mount Attachinary::Engine => "/attachinary"

  devise_for :buyers, controllers: { registrations: "registrations", omniauth_callbacks: 'buyers/omniauth_callbacks' }
  devise_for :sellers, controllers: { registrations: "registrations" }

  resources :buyers do
    resources :orders, only: [:new, :update]
  end

  resources :sellers do
    resources :products, only: [:index, :new, :create, :edit, :update]
    resources :orders, only: [:index, :show, :edit, :update]
  end
  resources :products, only: [:index, :show, :edit, :update, :destroy]
  resources :categories
  resources :orders, only: [:index, :show, :edit, :update]
  resources :baskets


  post "add_item/", to: "baskets#add_item"
  post "destroy_cookies_item/:product_id", to: "baskets#destroy_cookies_item", as: 'cookies'

  get "search", to: "products#search"

  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= asset_path("banner.jpg") %>');">
  <div class="banner-content">
    <h1>Build'n'Green</h1>
    <p>The place to build</p>

    <form action="search" method="GET">
      <label for="search_Word">De quel produit avez-vous besoin?</label>
      <input type="text" id="research" name="word" placeholder="votre recherche" class="form-control">
      <br>
      <input type="submit" name="search" class="btn btn-success">
    </form>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fa fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_form_buyer.html.erb
  <%= simple_form_for(@buyer) do |f| %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :email %>
    <%= f.input :address %>
    <%= f.submit "valider", class:'btn btn-primary' %>
  <% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <i class="fa fa-envira" aria-hidden="true"></i>
  Build'n'Green
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right">

    <!-- Links when logged in -->

    <!-- Personnalisation selon la connexion
    If I am a buyer -->
    <% if buyer_signed_in? %>

      <!-- Dropdown category -->
      <!-- <div class="dropdown">
        <button class="navbar-wagon-item navbar-wagon-link" data-toggle="dropdown"> Categories <span class="caret"></span></button>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <% Category.all.each do |category|%>
            <li>
              <%= link_to category.name, category_path(category) %>
            </li>
          <% end %>
        </ul>
      </div> -->
      <!-- Fin du Dropdown -->
      <%= link_to "Catégories", categories_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Produits", products_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Mon compte", buyer_path(current_buyer), class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Mes commandes", buyer_path(current_buyer), class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to baskets_path, class: "navbar-wagon-item navbar-wagon-link" do %>
        <div>Mon panier</div>
        <div><%= Basket.items(current_buyer.id) %></div>
      <% end %>
      <div class="navbar-wagon-item navbar-wagon-link">Bonjour <%= current_buyer.first_name %> ! <br>
        <%= link_to destroy_buyer_session_path, method: :delete do %>
          <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Deconnexion") %>
        <% end %>
      </div>

      <!-- If I am a seller -->
    <% elsif seller_signed_in? %>
      <%= link_to "Catégories", categories_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Mon compte", seller_path(current_seller, anchor: "info"), class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Mes commandes", seller_orders_path(current_seller), class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Mes produits", seller_products_path(current_seller), class: "navbar-wagon-item navbar-wagon-link" %>
      <div class="navbar-wagon-item navbar-wagon-link"><%= current_seller.company_name %> <br>
        <%= link_to destroy_seller_session_path, method: :delete do %>
          <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Deconnexion") %>
        <% end %>
      </div>

      <!-- Non loggé -->
    <% else %>
      <!-- Dropdown category -->
      <!-- <div class="dropdown">
        <button class="navbar-wagon-item navbar-wagon-link" data-toggle="dropdown"> Categories <span class="caret"></span></button>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <% Category.all.each do |category|%>
            <li>
              <%= link_to category.name, category_path(category) %>
            </li>
          <% end %>
        </ul>
      </div> -->
      <!-- Fin du Dropdown -->
      <%= link_to "Catégories", categories_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Produits", products_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "S'inscrire", new_buyer_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Se connecter", new_buyer_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to baskets_path, class: "navbar-wagon-item navbar-wagon-link" do %>
        <div>Panier</div>
        <div><%= "(#{session[:basket].length})" unless session[:basket].nil? %></div>
      <% end %>
      </div>
    <% end %>
  </div>
</div>