config/routes.rb
Rails.application.routes.draw do
  get 'baskets/show'

  mount Attachinary::Engine => "/attachinary"

  devise_for :buyers, controllers: { registrations: "registrations", omniauth_callbacks: 'buyers/omniauth_callbacks' }
  devise_for :sellers, controllers: { registrations: "registrations" }

  resources :buyers do
    resources :orders, only: [:new, :update]
  end

  resources :sellers do
    resources :products, only: [:index, :new, :create, :edit, :update]
    resources :orders, only: [:index, :show, :edit, :update]
  end
  resources :products, only: [:index, :show, :edit, :update, :destroy]
  resources :categories
  resources :orders, only: [:index, :show, :edit, :update]
  resources :baskets


  post "add_item/", to: "baskets#add_item"
  post "destroy_cookies_item/:product_id", to: "baskets#destroy_cookies_item", as: 'cookies'

  get "search", to: "products#search"

  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :buyer
  has_many :baskets
  has_many :products, through: :baskets

  def sum
    sum = 0
    baskets.each do |item|
      sum += item.product_price unless item.product_price.nil?
    end
    return sum
  end

  def tva
    return (sum*0.2/1.2).round(2)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
before_action :load_order, only: [:show, :update, :destroy, :edit, :update]
  def index
  end

  def show

  end

  def edit
    # see that later
    @order = Order.update(load_order)
  end

  def update
    @order.update(
      status: "validation en cours",
      address: @order.buyer.address,
      order_date: Time.now
      )
  end

  private

  def load_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:status, :buyer_id)
  end
end

app/views/orders/edit.html.erb
<div class="container">
  <div>Votre commande est validée !</div>
  <img src="http://static.deathandtaxesmag.com/uploads/2013/03/tumblr_mkd241kQgx1qzfsnio2_1280.jpg" alt="">
</div>

app/views/orders/index.html.erb
<div>
    <% if current_seller.orders.count == 0 %>
      <h2>Vous n'avez pas encore de commande :-( </h2>
      <div> <%= image_tag("/assets/sad_kitten.jpg") %>
      </div>

    <% else %>
      <table>
        <thead>
          <tr>
            <th class="th-header" >#-Réf</th>
            <th class="th-header" >Date</th>
            <th class="th-header" >Prénom</th>
            <th class="th-header" >Nom de famille</th>
            <th class="th-header" >Adresse de Livraison</th>
            <th class="th-header" >Prix (€)</th>
            <th class="th-header" >Statut</th>
            <th class="th-header" >Voir Détails</th>
          </tr>
        </thead>
        <tbody>
        <% current_seller.orders.order("created_at DESC").each do |order| %>
          <%= simple_form_for(order) do |f| %>
          <%= f.error_notification %>
          <tr>
            <td><%= order.id %></td>
            <td><%= order.order_date %></td>
            <td><%= order.buyer.first_name %></td>
            <td><%= order.buyer.last_name %></td>
            <td><%= order.buyer.address %></td>
            <td><%= order.sum %></td>
            <td><%= f.select :status, options_for_select(["En attente de validation", "Validé", "Livraison en cours", "Livré", "Annulé"]) %>
            <%= f.button :submit, "Mettre à jour" %>
            </td>
            <td><%= link_to "Détails", order_path(order), class:"btn btn-success" %></td>
          </tr>
          <% end %>
        <% end %>
        </tbody>
      </table>
    <% end %>
  </div>

app/views/orders/show.html.erb
<h1>Détail de la commande N°<%= @order.id %></h1>
<div>Statut de la commande : <%= @order.status %></div>
<div>Date de la commande : <%= @order.order_date %></div>
<br>
<div>Contenu de la commande : </div>
<table>
  <tr>
    <th>Photo</th>
    <th>Produit</th>
    <th>Vendeur</th>
    <th>ID</th>
    <th>Quantité</th>
    <th>Prix</th>
  </tr>
  <% @order.baskets.includes(:seller).each do |basket| %>
    <tr>
      <td></td>
      <td><%= basket.product.name %></td>
      <td><%= basket.seller.company_name %></td>
      <td><%= basket.id %></td>
      <td><%= basket.quantity %></td>
      <td><%= basket.product_price %>€</td>
    </tr>
  <% end %>
    <tr>
      <td></td>
      <td></td>
      <td colspan = 2>Total</td>
      <td><%= @order.sum  %>€</td>
    </tr>
    <tr>
      <td></td>
      <td></td>
      <td colspan = 2>Dont TVA</td>
      <td><%= @order.tva  %>€</td>
    </tr>
</table>

<% if buyer_signed_in? %>
<div><%= link_to "Retour aux commandes", buyer_path(current_buyer), class:"btn btn-primary" %></div>
<% elsif seller_signed_in? %>
<div><%= link_to "Retour aux commandes", seller_path(current_seller), class:"btn btn-primary" %></div>
<% end %>

app/views/orders/update.html.erb
<div class="container">
  <h2>Votre commande N°<%= @order.id %> est terminée !</h2>
  <div>Elle est en cours de validation</div>
  <img src="http://static.deathandtaxesmag.com/uploads/2013/03/tumblr_mkd241kQgx1qzfsnio2_1280.jpg" alt="">
  <div><%= link_to "retour accueil", root_path, class:"btn btn-success" %></div>
</div>