config/routes.rb
Rails.application.routes.draw do
  get 'baskets/show'

  mount Attachinary::Engine => "/attachinary"

  devise_for :buyers, controllers: { registrations: "registrations", omniauth_callbacks: 'buyers/omniauth_callbacks' }
  devise_for :sellers, controllers: { registrations: "registrations" }

  resources :buyers do
    resources :orders, only: [:new, :update]
  end

  resources :sellers do
    resources :products, only: [:index, :new, :create, :edit, :update]
    resources :orders, only: [:index, :show, :edit, :update]
  end
  resources :products, only: [:index, :show, :edit, :update, :destroy]
  resources :categories
  resources :orders, only: [:index, :show, :edit, :update]
  resources :baskets


  post "add_item/", to: "baskets#add_item"
  post "destroy_cookies_item/:product_id", to: "baskets#destroy_cookies_item", as: 'cookies'

  get "search", to: "products#search"

  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord

  mount_uploader :photo_1, PhotoUploader
  mount_uploader :photo_2, PhotoUploader
  mount_uploader :photo_3, PhotoUploader

  belongs_to :seller
  belongs_to :category
  has_many :baskets


  validates :name, presence: true
  validates :description, presence: true
  validates :selling_price, presence: true
  validates :retail_price, presence: true




end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  def index
    @products = Product.all
  end

  def search
    @word = params[:word]
    @productList = []
    Product.all.each do |product|
      @productList << product if product.name.downcase.include?(@word.downcase)
    end
    p @productList

  end

  def show
    @seller = @product.seller
  end

  def new
    @product = Product.new
    @seller = Seller.find(params[:seller_id])
  end

  def edit
  end

  def update
    @product.update(product_params)
    unless request.referrer == seller_url
      redirect_to @product
    end
  end

  def create
    @product = Product.new(product_params)
    @product.seller = Seller.find(params[:seller_id])
    @product.save
    redirect_to @product
  end

  def destroy
    @product.destroy
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
     params.require(:product).permit(:name, :description, :stock, :material, :color, :size, :weight, :selling_price, :retail_price, :vat, :seller_id, :category_id, :photo_1, :photo_1_cache, :photo_2, :photo_2_cache, :photo_3, :photo_3_cache)
  end
end

app/views/products/_form.html.erb
<div id="container-form">
  <%= link_to 'Back', products_path %>
  <%= simple_form_for [@seller, @product] do |f| %>
   <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, label: "Titre"  %>
  </div>

    <div class="form-inputs">
    <%= f.input :description %>
  </div>

  <div class="form-inputs">
    <%= f.input :category_id, label: "Catégorie", collection: Category.all %>
  </div>

  <div class="form-inputs">
    <%= f.input :selling_price, label: "Prix de vente TTC" %>
  </div>

  <div class="form-inputs">
    <%= f.input :retail_price, label: "Prix barré" %>
  </div>

  <div class="form-inputs">
    <%= f.input :vat, label: "TVA %" %>
  </div>

  <div class="form-inputs">
    <%= f.input :stock, label: "Quantité" %>
  </div>

  <div class="form-inputs">
    <%= f.input :photo_1 %>
    <%= f.input :photo_1_cache, as: :hidden %>

    <% if !current_page?(new_seller_product_path) %>
      <% if !product.photo_1.nil?%>
      <%= cl_image_tag @product.photo_1.url(:thumbnail) %>
      <% end %>

    <% end %>
  </div>
  <div class="form-inputs">
    <%= f.input :photo_2 %>
    <%= f.input :photo_2_cache, as: :hidden %>
    <% if !current_page?(new_seller_product_path) %>
      <% if !product.photo_2.nil?%>
        <%= cl_image_tag @product.photo_2.url(:thumbnail) %>
      <% end %>
    <% end %>
  </div>
  <div class="form-inputs">
    <%= f.input :photo_3 %>
    <%= f.input :photo_3_cache, as: :hidden %>
    <% if !current_page?(new_seller_product_path) %>
      <% if !product.photo_3.nil?%>
        <%= cl_image_tag @product.photo_3.url(:thumbnail) %>
      <% end %>
    <% end %>
  </div>

  <div class="form-actions">

    <%= f.button :submit, "Ajouter" %>

  </div>

<% end %>

</div>

app/views/products/_seller_products_index.html.erb
 <h3>Mes Produits</h3>
    <%= link_to "Ajouter un Produit", new_seller_product_path(current_seller), class:"btn btn-primary" %>
    <% if current_seller.products.count == 0 %>
      <h2>Vous n'avez pas encore de commande :-( </h2>
      <div> <%= image_tag("sad_kitten.jpg") %>
      </div>
      <div>
        <%= link_to "Découvrez nos meilleurs produits", root_path %>
      </div>
    <% else %>
       <table>
        <thead>
          <tr>
            <th class="th-header" ># Réf</th>
            <th class="th-header" >Titre</th>
            <th class="th-header" >Prix barré</th>
            <th class="th-header" >Prix de vente</th>
            <th class="th-header" >Quantité</th>
            <th class="th-header" >Détails</th>
            <!-- <th class="th-header" ></th> -->
          </tr>
        </thead>
        <tbody>
        <% current_seller.products.order(:id).each do |product| %>
          <%= simple_form_for(product) do |f| %>
          <%= f.error_notification %>
          <tr>

            <td><%= product.id %></td>
            <td><%= f.input :name, label: false %></td>
            <td><%= f.input :retail_price, label: false %></td>
            <td><%= f.input :selling_price, label: false %></td>
            <td><%= f.input :stock, label: false %></td>
            <td>
              <%= link_to "Détails", product_path(product), class:"btn btn-primary" %>
              <%= f.button :submit, "Mettre à jour" %>
            </td>
           <!--  <td> <%= link_to "supprimer", product_path(product), method: :delete, data: { confirm: "Êtes-vous sûr(e)?" } %></td> -->
          </tr>
          <% end %>
        <% end %>
        </tbody>
      </table>
    <% end %>

app/views/products/edit.html.erb
<h1>Product Edit</h1>
<h1><%= @product.name %></h1>

<%= render 'form', product: @product, seller: @seller %>

app/views/products/index.html.erb
  <% if !current_page?(products_path) %>
    <%= render "seller_products_index" %>
  <% else %>

   <div class="container-fluid">
    <div class="separator">
    <h2>Tous nos produits</h2>
    </div>
    <div class="row">
      <% @products.each do |product| %>
      <div class="col-xs-12 col-sm-4">
        <div class="card-product">
          <div class="card-product-body" style="background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.2)), url('<%= asset_path("product/#{[product.id % 10, 1].max}.jpg") %>'); ">
            <% if product.name.length > 30 %>
                <span class="card-product-category"><%= product.name.first(30) %>...</span>
            <% else %>
                <span class="card-product-category"><%= product.name %></span>
            <% end %>
            <div class="card-product-description">
              <h2><%= product.category.name %></h2>
            </div>
            <img class="card-product-user avatar" src="images/jad.png">
            <a class="card-product-link" href="<%= product_path(product) %>"></a>
          </div>
          <div class="card-product-footer">
           <p><i class="fa fa-tags" aria-hidden="true"></i> <strong><%= product.selling_price %> euros</strong></p>
            <div class="controls">
                <i id="<%= product.id %>" class="fa fa-cart-plus" aria-hidden="true"></i>
            </div>
          </div>
        </div>
        </div>
        <% end %>
      </div>
    </div>

<% end %>

app/views/products/new.html.erb
<h1>Nouveau Produit</h1>
<%= link_to "Retour", :back %>
<div class="container">
  <div class="row">
    <div class="col-xs-6 offset-xs-2">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/products/search.html.erb
<div class="container-fluid">
    <div class="separator">
    <h2>Résultats pour "<%= params[:word] %>"</h2>
    </div>
    <div class="row">
      <% @productList.each do |product| %>
      <div class="col-xs-12 col-sm-4">
        <div class="card-product">
          <div class="card-product-body" style="background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.2)), url('<%= asset_path("product/#{product.id % 10}.jpg") %>'); ">
              <% if product.name.length > 30 %>
                <span class="card-product-category"><%= product.name.first(30) %>...</span>
            <% else %>
                <span class="card-product-category"><%= product.name %></span>
            <% end %>
            <div class="card-product-description">
              <h2><%= product.category.name %></h2>
            </div>
            <img class="card-product-user avatar" src="images/jad.png">
            <a class="card-product-link" href="<%= product_path(product) %>"></a>
          </div>
         <div class="card-product-footer">
           <p><i class="fa fa-tags" aria-hidden="true"></i> <strong><%= product.selling_price %> euros</strong></p>
            <div class="controls">
                <i id="<%= product.id %>" class="fa fa-cart-plus" aria-hidden="true"></i>
            </div>
          </div>
        </div>
        </div>
        <% end %>

      </div>
    </div>

app/views/products/show.html.erb
<div class="container">
  <div class="row" id="row-show-product">
    <div class="col-md-6 col-md-offset-3" >
      <div id="titre" style="border-bottom: 3px solid lightgrey "><h1><%=  @product.name %></h1></div>
    </div>

  <div>

    <div class="col-md-6" >
  <!-- image du produit vers la gauche (choisi une image par defaut pour tout les produits-->
    <!-- La category sous l'image -->
      <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
          <li data-target="#carousel-example-generic" data-slide-to="1"></li>
          <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        </ol>
        <!-- Wrapper for slides -->
        <div class="carousel-inner" id="images" role="listbox">
          <div class="item active">
            <%= cl_image_tag @product.photo_1.url %>
          </div>
          <div class="item">
            <%= cl_image_tag @product.photo_2.url %>
          </div>
          <div class="item">
            <%= cl_image_tag @product.photo_3.url %>
          </div>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>

      <ul id="category">
        <li><h5>Category:</h5> <%= @product.category[:name] %></li>
        <li><h5>Seller:</h5> <%= @product.seller[:first_name] %> <%= @product.seller[:last_name] %></li>

      </ul>
    </div>
  <!-- price vers la droite -->
    <div class="col-md-6">

      <div id="price">

    <% if current_seller == @product.seller %>

        <%= link_to 'Edit Product', edit_seller_product_path(@seller), class: "btn btn-warning" %>

      <% end %>

        <ul>
          <li><h4>Retail price:</h4> <%= @product.retail_price %> euros</li>
          <li><h5>Selling price:</h5> <%= @product.selling_price %> euros</li>
            <div id="description">
              <li>Description: <%= @product.description %></li>
            </div>
            <div class="form-group">
              <label for="sel1">Quantité:</label>
              <select class="form-control" id="quantity">
                <% 10.times do |i| %>
                <option><%= i + 1 %></option>
                <% end %>
              </select>
            </div>


            </ul>
            <div class="row">
              <div class="col-md-6 col-md-offset-5" >
                <div class= "add-basket btn btn-success", id="<%= @product.id %>">Ajouter au panier</div>
              </div>
            </div>
            <div id="other-products">
            <%= "Autre produits du vendeur:" %>
            </div>
            <% @seller.products.sample(3).each do |product|%>
              <%= link_to product_path(product) do %>
                <%= cl_image_tag product.photo_1.url(:preview) %>
              <% end %>
            <% end %>
<div>
    <%= link_to 'Edit Product', edit_seller_product_path(@seller), class: "btn btn-warning" %>
  </div>

    </div>
  </div>
  </div>
</div>